name: Build Images

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  filters:
    runs-on: ubuntu-latest
    outputs:
      main: ${{ steps.filter.outputs.main }}
      minimal: ${{ steps.filter.outputs.minimal }}
    steps:
      - 
        uses: actions/checkout@v2
      - 
        uses: dorny/paths-filter@v2.5.0
        id: filter
        with:
          filters: '.github/filters.yml'

  docker_build:
    runs-on: ubuntu-latest
    needs: filters
    if: ${{ needs.filters.outputs.main == 'true' }}
    
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Get OctoPrint Stable
        id: latest-octoprint
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: OctoPrint
          repo: OctoPrint
          excludes: prerelease,draft
      - 
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm,arm64
      - 
        name: Run a Test Build
        id: build
        uses: docker/build-push-action@v2
        with:
          push: false
          cache-from: type=registry,ref=octoprint/octoprint:cache
          cache-to: type=inline
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          build-args: |
            octoprint_ref=${{ steps.latest-octoprint.outputs.release }}

